In [1]:
import numpy as np

np.random.seed(0)
random_array = np.random.rand(5)
random_array

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [3]:
random_array

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [6]:
n = 5
array = np.random.randint(-10, 11, (n, 2)) # -10부터 10까지의 랜덤한 정수를 n x 2 배열로 생성
array

array([[  8,  -7],
       [  7,   9],
       [  9,   9],
       [  4,  -3],
       [-10,  -9]])

In [7]:
col_avg = np.mean(array, axis=0) # 열별 평균
col_avg

array([ 3.6, -0.2])

In [8]:
row_avg = np.mean(array, axis=1) # 행별 평균
row_avg

array([ 0.5,  8. ,  9. ,  0.5, -9.5])

In [9]:
arr = np.array([[1, 2], [-3, 4], [5, 6]]) # 세개의 좌표가 있는 2차원 배열
distances = np.linalg.norm(arr, axis=1)   # 각 좌표와 원점(0, 0) 사이의 거리를 계산하기
distances

array([2.23606798, 5.        , 7.81024968])

In [14]:
arr

array([[ 5,  6],
       [-3,  4],
       [ 1,  2]])

In [10]:
# np.argsort(배열) 배열을 정렬했을 때의 인덱스를 반환
sorted_indices = np.argsort(distances) 
sorted_indices

array([0, 1, 2])

In [12]:
sorted_indeces_desc = sorted_indices[::-1] # 내림차순 정렬
sorted_indeces_desc

array([2, 1, 0])

In [13]:
arr = arr[sorted_indeces_desc] # 정렬된 인덱스로 배열을 정렬
arr

array([[ 5,  6],
       [-3,  4],
       [ 1,  2]])

In [15]:
arr = arr[sorted_indices]
arr

array([[ 5,  6],
       [-3,  4],
       [ 1,  2]])